//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public Building()
        {
            this.Floors = new HashSet<Floor>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> NoOfFloors { get; set; }
        public Nullable<int> NoOfRooms { get; set; }
        public Nullable<System.DateTime> DateOfConstruction { get; set; }
        public Nullable<int> ConstructionCost { get; set; }
        public Nullable<System.DateTime> OccupancyPermitDate { get; set; }
        public Nullable<int> LandId { get; set; }
        public Nullable<int> BuildTypeId { get; set; }
        public Nullable<int> BuildingStatusId { get; set; }
    
        public virtual BuildingStatus BuildingStatus { get; set; }
        public virtual BuildingType BuildingType { get; set; }
        public virtual Land Land { get; set; }
        public virtual ICollection<Floor> Floors { get; set; }
    }
}
