//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Land
    {
        public Land()
        {
            this.Buildings = new HashSet<Building>();
            this.LandHistories = new HashSet<LandHistory>();
        }
    
        public int Id { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public string LandMarks { get; set; }
        public Nullable<int> AreaSize { get; set; }
        public Nullable<System.DateTime> PurchasedDate { get; set; }
        public Nullable<int> PurchasedCost { get; set; }
        public Nullable<int> PresentCost { get; set; }
        public Nullable<System.DateTime> BuildingPermitDate { get; set; }
        public Nullable<int> LandStatusId { get; set; }
    
        public virtual ICollection<Building> Buildings { get; set; }
        public virtual ICollection<LandHistory> LandHistories { get; set; }
        public virtual LandStatus LandStatus { get; set; }
    }
}
