//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandHistory
    {
        public int Id { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> LandId { get; set; }
    
        public virtual Land Land { get; set; }
    }
}
