//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AreaSqFt { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<int> RoomTypeId { get; set; }
    
        public virtual Floor Floor { get; set; }
        public virtual RoomType RoomType { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
