//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public Sale()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string BuyerName { get; set; }
        public string BuyerAddress { get; set; }
        public Nullable<int> PriceSqFt { get; set; }
        public Nullable<int> PaymentModeId { get; set; }
        public Nullable<int> SalesStatusId { get; set; }
        public Nullable<int> RoomId { get; set; }
    
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Room Room { get; set; }
        public virtual SalesStatus SalesStatus { get; set; }
    }
}
